from pathlib import Path
p=Path(__file__).resolve().parent;root=p.parent.parent;skill=Path('/Users/Apple/.codex/skills/app-designer')
font=(root/'assets/fonts/archivo/ScoutvyDisplay-Bold.ttf').as_uri();body=(root/'assets/fonts/InterDisplay-Regular.ttf').as_uri()
css='''
:root{--ground:#111111;--raised:#222222;--ink:#fff;--ink-2:#b3b3b3;--accent:#ab9ff3;--on-accent:#121022;--rule:#383838}
@font-face{font-family:Scoutvy;src:url(FONT)} @font-face{font-family:Reading;src:url(BODY)}
.screen{background:var(--ground);color:var(--ink);font-family:Reading,sans-serif}.screen[data-theme=dark]{color:var(--ink)}
.app{padding:calc(var(--safe-top) + 14px) 20px 0;height:100%;display:flex;flex-direction:column;gap:24px}
h1,h2,p{margin:0}h1{font:700 34px/1.1 Scoutvy;letter-spacing:-1px}h2{font:700 22px/1.2 Scoutvy;letter-spacing:-.5px}p{font-size:15px;line-height:1.5;color:var(--ink-2)}
header{flex-shrink:0;display:flex;align-items:center;justify-content:space-between;gap:16px}button{font:600 15px Reading;min-height:48px;padding:12px 20px;border:0;border-radius:28px;background:var(--accent);color:var(--on-accent)}
.ghost{background:var(--raised);color:var(--ink)}.search{background:var(--raised);border-radius:12px;padding:14px 16px;color:var(--ink-2);font-size:15px}
.segment{display:flex;background:var(--raised);border-radius:16px;padding:4px;gap:4px}.segment button{flex:1;border-radius:12px;background:transparent;color:var(--ink-2)}.segment .active{background:var(--accent);color:var(--on-accent)}
.controls{display:flex;align-items:center;justify-content:space-between;gap:12px}.meta{font-size:13px;color:var(--ink-2)}.quiet{background:transparent;color:var(--ink-2);padding:8px;min-height:44px}
.empty{flex:1;display:flex;align-items:flex-start;justify-content:center;gap:16px;flex-direction:column;min-height:0}.browse-empty{overflow:auto;flex-shrink:1;justify-content:flex-start;padding:24px 0 16px}.browse-empty>*{flex-shrink:0}.empty h2{max-width:290px}.empty p{max-width:300px}.focus{width:156px;height:128px;flex-shrink:1;min-height:60px;align-self:flex-start}
nav{flex-shrink:0;position:relative;z-index:1;display:flex;background:var(--raised);border:1px solid var(--rule);border-radius:28px;padding:6px;justify-content:space-around;gap:4px;margin-bottom:calc(var(--safe-bottom) + 8px);min-height:64px}nav span{flex:1;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center;font-size:11px;gap:4px;color:var(--ink-2);min-width:0}nav .sel{background:#37333f;color:var(--accent);border-radius:22px}svg.icon{width:21px;height:21px;stroke:currentColor;fill:none;stroke-width:1.7}
.hero{padding:20px;position:relative;display:flex;flex-direction:column;gap:12px}.hero:before,.hero:after{content:"";position:absolute;width:18px;height:18px;border-color:var(--rule);border-style:solid;pointer-events:none}.hero:before{left:0;top:0;border-width:1px 0 0 1px;border-radius:8px 0 0 0}.hero:after{right:0;bottom:0;border-width:0 1px 1px 0;border-radius:0 0 8px 0}.amount{font:700 56px/1.1 Scoutvy;letter-spacing:-1.7px;font-variant-numeric:tabular-nums}.amount small{font:400 22px Reading;color:var(--ink-2);letter-spacing:0}.tag{font-size:13px;color:#00c088}.line{padding:18px 0;border-bottom:1px solid var(--rule);display:flex;gap:16px;align-items:center}.line .copy{flex:1}.line strong{font-size:17px}.line p{margin-top:4px;font-size:13px}.token{width:36px;height:36px;border-radius:50%;background:#2878c8;color:white;display:grid;place-items:center;font-size:22px}.scroll{flex:1;min-height:0;overflow:auto;padding-bottom:32px;display:block}.section{font-size:13px;color:var(--ink-2);margin:24px 0 8px}.field{border:1px solid var(--rule);border-radius:12px;background:var(--raised);min-height:54px;padding:16px;margin:8px 0 24px;color:var(--ink-2);font-size:15px}.footer{flex-shrink:0;position:relative;z-index:1;background:var(--ground);padding-top:8px;box-shadow:0 -12px 12px var(--ground);padding-bottom:calc(var(--safe-bottom) + 12px);display:grid;gap:12px}.footer button{width:100%}.back{font-size:22px;width:44px;height:44px;display:grid;place-items:center;background:var(--raised);border-radius:50%}.inline-title{font-size:17px;flex:1}.rules{display:grid;gap:24px;padding:24px 0}.rules label{color:var(--ink-2);font-size:13px;display:block;margin-bottom:8px}.rules div{font-size:17px}.hero-art{max-height:240px;width:100%;object-fit:contain}.onboard{justify-content:center;text-align:center}.onboard .hero-art{max-height:220px}.onboard h1{font-size:34px}.onboard p{max-width:320px}.onboard.empty{align-items:center}
.light{--ground:#f5f7f6;--raised:#e4ebe8;--ink:#182624;--ink-2:#536360;--accent:#0a7469;--on-accent:#fff;--rule:#c3d1cc}.light h1,.light h2{font-family:var(--ny)}.signal{--ground:#ed6b38;--raised:#d55729;--ink:#17181c;--ink-2:#170c07;--accent:#203ba3;--on-accent:#fff;--rule:#a44929}.signal h1,.signal h2{font-family:var(--sf-rounded);font-weight:800}.signal .focus{background:#ef986c;border-radius:36px}.mini-step{background:#222;border-radius:20px;padding:20px;display:grid;gap:12px}.story{padding:40px 20px}.story .segment{background:#333}.app-icon{background:#111;display:grid;place-items:center}.app-icon img{width:70%}.before img{width:100%;height:100%;object-fit:cover}.before{background:#111}
@container(max-height:760px){.app{gap:16px;padding-top:calc(var(--safe-top) + 8px)}.empty{gap:12px}.focus{width:112px;height:80px}.hero{padding:12px 0}.onboard .hero-art{max-height:155px}.onboard h1{font-size:28px}nav{margin-bottom:var(--safe-bottom)}}
'''.replace('FONT',font).replace('BODY',body)
(p/'study.css').write_text(css)
def icon(kind):
 paths={'Explore':'<circle cx="12" cy="12" r="8"/><path d="m15 9-2 4-4 2 2-4Z"/>','Wallet':'<rect x="3" y="5" width="18" height="15" rx="4"/><path d="M16 10h5v5h-5z"/>','Activity':'<path d="M3 13h4l3-7 4 12 3-5h4"/>','Profile':'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-9 16-9 16 0"/>'}
 return '<svg class="icon" viewBox="0 0 24 24">'+paths[kind]+'</svg>'
def nav(active='Explore'):return '<nav data-system>'+''.join('<span class="'+('sel' if k==active else '')+'">'+icon(k)+k+'</span>' for k in ['Explore','Wallet','Activity','Profile'])+'</nav>'
focus='''<svg class="focus" viewBox="0 0 156 128" fill="none" aria-hidden="true"><path d="M35 16H20q-8 0-8 8v16M121 16h15q8 0 8 8v16M12 88v16q0 8 8 8h15M144 88v16q0 8-8 8h-15" stroke="currentColor" stroke-width="2" opacity=".35"/><rect x="35" y="32" width="86" height="64" rx="14" fill="currentColor" opacity=".07"/><path d="M55 49h34M55 60h24" stroke="currentColor" stroke-width="3" stroke-linecap="round" opacity=".4"/><circle cx="108" cy="84" r="20" fill="var(--accent)"/><path d="m108 76 0 16m-8-8h16" stroke="var(--on-accent)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>'''
def core(cls=''):
 return '<div class="app"><header><h1>Explore</h1><button>Post</button></header><div class="search">Search bounties</div><div class="segment"><button class="active">Online</button><button>Nearby</button></div><div class="controls"><span class="meta">0 bounties · Online</span><button class="quiet">Filters &amp; sort</button></div><div class="empty browse-empty" data-scrolls>'+focus+'<h2>No online bounties yet</h2><p>Post a task for someone to complete from anywhere.</p><button>Post a bounty</button></div>'+nav()+'</div>'
def screen(name,html,cls='',attrs=''):return f'<section class="screen {cls}" data-name="{name}" data-theme="dark" data-chrome="{'none' if name == 'signature' else 'dark' if cls in ('light','signal') else 'light'}" {attrs}>{html}</section>'
def page(name,html):
 (p/name).write_text(f'<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="{skill.as_uri()}/assets/device.css"><link rel="stylesheet" href="study.css"></head><body>{html}<script src="{skill.as_uri()}/assets/device.js"></script></body></html>')
page('explore.html',screen('Focus',core())+screen('Field-guide',core().replace(focus,'<div style="font:700 72px var(--ny);border-top:2px solid;padding-top:16px">0<span style="font:400 15px Reading"> open tasks</span></div>'),'light')+screen('Signal',core().replace(focus,'<div style="height:110px;width:100%;background:#ed9b73;border-radius:40px 8px;display:flex;align-items:center;padding:24px;font:800 42px var(--sf-rounded)">Open call.</div>'),'signal'))
before=screen('before-explore',f'<img src="{(root/"artifacts/ui-consistency/01-explore.png").as_uri()}"/>','before','data-home="light"')
page('before.html',before)
page('before-after.html',before+screen('after-explore',core()))
wallet='<div class="app"><header><h1>Wallet</h1></header><span class="meta">BraveScout1056 · 6sTy…Rtg</span><div class="hero"><span class="meta">Available · Test mode</span><div class="amount">18 <small>USDC</small></div><p>Available balance, excluding escrow.</p></div><div style="display:flex;gap:12px"><button style="flex:1">Receive</button><button class="ghost" style="flex:1">Explorer</button></div><div class="scroll" data-scrolls><h2>Tokens</h2><div class="line"><img class="token" src="file:///Users/Apple/Documents/ChatGPT/scoutvy/assets/images/tokens/usdc.png"><div class="copy"><strong>USDC</strong><p>USD Coin</p></div><strong>18</strong></div><div class="line"><img class="token" src="file:///Users/Apple/Documents/ChatGPT/scoutvy/assets/images/tokens/skr.png"><div class="copy"><strong>Seeker</strong><p>SKR</p></div><strong>0</strong></div><div class="section">SOL balance</div><p>9.958400242 SOL</p></div>'+nav('Wallet')+'</div>'
detail='<div class="app"><header><span class="back">‹</span><span class="inline-title">Bounty details</span></header><div class="hero"><span class="tag">Reward paid</span><div class="amount">1 <small>USDC</small></div><span class="meta">Test mode</span></div><div class="scroll" data-scrolls><h2>Devnet written bounty payout</h2><div class="rules"><div><label>Requirements</label>Submit a written confirmation of this Devnet integration check. No physical visit required.</div><div><label>Work type</label>Online</div><div><label>Submission</label>Written response or work link</div></div></div><div class="footer" data-float><button class="ghost">View escrow on Explorer</button><button>View submission</button></div></div>'
post='<div class="app"><header><span class="back">‹</span><span class="inline-title">Post a bounty</span><span class="meta">1 of 5</span></header><div class="scroll" data-scrolls><h1>What do you need?</h1><p style="margin:12px 0 32px">Set the task and what counts as complete.</p><label>Title</label><div class="field">Give your bounty a clear title</div><label>Requirements</label><div class="field" style="min-height:136px">Describe what needs to be done and how you’ll review it.</div><label>Where can it be done?</label><div class="segment" style="margin-top:12px"><button class="active">Online</button><button>At a location</button></div><p class="section">What should be submitted?</p><div class="field" style="color:var(--ink)">Written response or work link</div></div><div class="footer" data-float><button style="opacity:.5">Choose reward</button></div></div>'
profile='<div class="app"><h1>Profile</h1><div class="hero"><h2>BraveScout1056</h2><span class="meta">6sTy…Rtg · Scout</span></div><div class="scroll" data-scrolls>'+''.join(('<div class="section">Preferences</div>' if x=='Notifications' else '<div class="section">Account</div>' if x=='Help' else '')+'<div class="line"><strong class="copy">'+x+'</strong><span>›</span></div>' for x in ['Username','My bounties','Seeker verification','Notifications','Permissions','Blocked users','Help','Your data','Sign out'])+'</div>'+nav('Profile')+'</div>'
intro='<div class="app"><header><span class="meta">scoutvy</span><button class="quiet">Skip</button></header><div class="empty onboard"><img class="hero-art" src="'+(root/'design/onboarding-preview/art/brief.svg').as_uri()+'"><h1>Your task.<br>Your terms.</h1><p>Set the requirements.<br>Choose what counts as complete.</p></div><div class="footer" data-float><button>Continue</button><p class="meta" style="text-align:center">Test mode · No real-money rewards</p></div></div>'
story='<div class="app story"><h1>Shift the focus</h1><p>One selection. The same workspace.</p>'+''.join('<div class="mini-step"><span class="meta">'+t+'</span><div class="segment" style="position:relative">'+('<span style="position:absolute;left:40%;top:4px;bottom:4px;width:54%;background:var(--accent);border-radius:12px"></span>' if '120' in t else '')+'<button style="position:relative" class="'+a+'">Online</button><button style="position:relative" class="'+b+'">'+('<span style="background:var(--accent);color:var(--on-accent)">Nearby</span>' if '120' in t else 'Nearby')+'</button></div></div>' for t,a,b in [('0 ms · Online','active',''),('120 ms · Moving','',''),('320 ms · Nearby','','active')])+'<p>Selection haptic on change.<br>Reduced motion: instant selection.</p></div>'
mark=(root/'assets/images/scoutvy-mark.png').as_uri()
page('mockup.html',screen('explore',core())+screen('bounty',detail)+screen('wallet',wallet)+screen('post',post)+screen('profile',profile)+screen('introduction',intro)+screen('signature',story,attrs='data-dense data-chrome="none"')+f'<section class="app-icon" data-name="existing-mark"><img src="{mark}"></section>')
